version: '3'

services:
  db:
    image: postgres:11.1-alpine
    container_name: postgres01
  # nginx:
  #   image: nginx:1.13-alpine
  #   container_name: nginx01
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./project:/src
  #     - ./config/nginx:/etc/nginx/conf.d
  #   depends_on:
  #     - web
  web:
    build: .
    container_name: django01
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - db
    volumes:
      - ./project:/src
    ports:
      - "8080:8080"
    restart: always
